import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const open_sans = Open_Sans({
  subsets: ["latin", "greek"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-100">
          <div className="h-24 ">
            <Navbar />
          </div>
          <div className="h-[calc(100vh-6rem)] justify-center">{children}</div>
        </div>
      </body>
    </html>
  );
}
