import { Open_Sans } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

const open_sans = Open_Sans({
  subsets: ["latin", "greek"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-helfont font-100">
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
